config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pics#index'
  resources :pics do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pic
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments
  has_one_attached :image

  def self.search(search)
    if search != ""
      Pic.where('text Like(?)', "%#{search}%")
    else
      Pic.all 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pics
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/pics/#{comment.pic.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, pic_id: params[:pic_id])
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]
  def index
    @pics = Pic.includes(:user).order("created_at DESC")
  end

  def new
    @pic = Pic.new
  end

  def create
    Pic.create(pic_params)
  end

  def destroy
    pic = Pic.find(params[:id])
    pic.destroy
  end

  def edit
  end

  def update
    pic = Pic.find(params[:id])
    pic.update(pic_params)
  end

  def show
    @comment = Comment.new
    @comments = @pic.comments.includes(:user)
  end 

  def search
    @pics = Pic.search(params[:keyword])
  end

  private
  def pic_params
    params.require(:pic).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_pic
    @pic = Pic.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @pics = current_user.pics
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myanpic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">MyanPic</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_pic_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright MyanPic 2022.
      </p>
    </footer>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_with(model: pic, local: true) do |form| %>
      <%= form.file_field :image, placeholder: "Image", id:"pic_image" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>

app/views/pics/_pic.html.erb
    <div class="content_post" >
      <%= pic.image %>
    <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
        <li>
            <%= link_to '詳細', pic_path(pic.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == pic.user_id %>
            <li>
              <%= link_to '編集', edit_pic_path(pic.id), method: :get %>
            </li>
            <li>
              <%= link_to '削除', pic_path(pic.id), method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
      <p><%= pic.text %></p>
      <span class="name">
        <a href="/users/<%= pic.user.id %>">
          <span>投稿者</span><%= pic.user.nickname %>
        </a>
      </span>
    </div>

app/views/pics/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/pics/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/pics/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { pic: @pic } %>
  </div>
</div>

app/views/pics/index.html.erb
<%= form_with(url: search_pics_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @pics.each do |pic| %>
    <%= render partial: "pic", locals: { pic: pic} %>
  <% end %>
</div>

app/views/pics/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { pic: @pic } %>
  </div>
</div>

app/views/pics/search.html.erb
<%= form_with(url: search_pics_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @pics.each do |pic| %>
    <%= render partial: "pic", locals: { pic: pic } %>
  <% end %>
</div>

app/views/pics/show.html.erb
<div class="contents row">
  <div class="content_post" >
    <%= image_tag @pic.image %>
    <% if user_signed_in? && current_user.id == @pic.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_pic_path(@pic.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', pic_path(@pic.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <p><%= @pic.text %></p>
    <span class="name">
      <a href="/users/<%= @pic.user.id %>">
        <span>投稿者</span><%= @pic.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@pic, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/pics/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @pics.each do |pic| %>
    <%= render partial: "pics/pic", locals: { pic: pic} %>
  <% end %>
</div>